app = 'solana-gym'
primary_region = 'jnb'

[build]

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[restart]
  policy = 'always'
